POST http://localhost:3001/api/save
Content-Type: application/json

{
    "title":"Hello",
    "author":"AuthorTest",
    "journalName": "Hello2",
    "year":"01/01/2000",
    "volume": "4",
    "number": "1234",
    "pages": "12-15",
    "doi":"test",
    "SE_practice":"TDD"
    
    
}